import { STORE } from "./storeIdentity";

// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: STORE.name,
  domain: STORE.domainHost,
  city: STORE.city,
  province: STORE.region,
  country: STORE.country,
  slug: "weed-dispensary-toronto",
  address: STORE.addressLine,
  streetAddress: STORE.streetAddress,
  postalCode: STORE.postalCode,
  phone: STORE.phoneDisplay,
  phoneIntl: STORE.phoneE164,
  neighborhood: "Little Jamaica / Fairbank",
  nearbyAreas: [
    "Eglinton Ave W",
    "Little Jamaica",
    "Fairbank",
    "Oakwood Village",
    "Dufferin St",
    "Oakwood Ave",
    "Eglinton West Station",
    "TTC 32 Eglinton West",
  ],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "/visit",
  mapEmbedUrl: STORE.mapEmbedUrl,
  latitude: String(STORE.latitude),
  longitude: String(STORE.longitude),
  hours: [STORE.hoursLabel],
  seoTitle: "First Nation Smoke Cannabis | Toronto Dispensary on Eglinton West",
  metaDescription: "First Nation Smoke is the adult 19+ walk-in at 1504 Eglinton Ave W on Eglinton West through Little Jamaica and Fairbank. Open 24 Hours.",
  localLandmarks: ["Eglinton Ave W", "Little Jamaica", "Fairbank", "Dufferin St", "Oakwood Ave"],
  introVariant: "First Nation Smoke is the Eglinton West walk-in at 1504 Eglinton Ave W, on the Little Jamaica and Fairbank stretch near Dufferin Street and Oakwood Avenue. Adults 19+ can review flower, pre-rolls, edibles, vapes, concentrates, accessories, and listed cigarettes on the current menu. Use the homepage for hours and the map; use /visit for how to reach the door.",
  neighborhoodDescription: "1504 Eglinton Ave W sits on the Eglinton West retail strip through Little Jamaica and Fairbank, with Oakwood Avenue to the east and Dufferin Street close on the same frontage. Oakwood Village, Caledonia, and Marlee are the nearby residential names on this corridor.",
  parkingNote: "Street parking on Eglinton Avenue West; evening curb space is often easier than midday. Read the signs on the block you stop on",
  transitNote: "Eglinton West Station (Line 1) is the subway anchor; finish west on Eglinton Avenue West via the 32 Eglinton West bus, or use Dufferin buses to the Eglinton corner",
  sectionTitle: "Eglinton West shoppers near Little Jamaica and Fairbank"
};
