// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "First Nation Smoke Cannabis Dispensary Toronto",
  domain: "firstnationsmokez.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "1504 Eglinton Ave W, Toronto, ON M6E 2G5",
  streetAddress: "1504 Eglinton Ave W",
  postalCode: "M6E 2G5",
  phone: "(437) 215-1466",
  phoneIntl: "+14372151466",
  neighborhood: "Little Jamaica / Fairbank",
  nearbyAreas: ["Eglinton Ave W", "Little Jamaica", "Fairbank", "Oakwood Village", "Dufferin St", "Eglinton West Station", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://www.google.com/maps/search/?api=1&query=1504%20Eglinton%20Ave%20W%2C%20Toronto%2C%20ON%20M6E%202G5",
  mapEmbedUrl: "https://maps.google.com/maps?q=First%20Nation%20Smoke%20Cannabis%20Dispensary%20Toronto%201504%20Eglinton%20Ave%20W%2C%20Toronto%2C%20ON%20M6E%202G5&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6979500",
  longitude: "-79.4409900",
  hours: ["Open 24 Hours"],
  seoTitle: "First Nation Smoke Cannabis Dispensary Toronto | Weed Dispensary in Toronto",
  metaDescription: "First Nation Smoke Cannabis Dispensary Toronto is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service fo...",
  localLandmarks: ["Eglinton Ave W", "Little Jamaica", "Fairbank"],
  introVariant: "First Nation Smoke Cannabis Dispensary Toronto is a local weed dispensary in Toronto, located at 1504 Eglinton Ave W. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Little Jamaica / Fairbank, a cannabis store in Toronto, or a local weed shop close to Little Jamaica, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Little Jamaica / Fairbank district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking and public parking spaces are available nearby",
  transitNote: "Served by local TTC bus routes along Eglinton Avenue West.",
  sectionTitle: "Serving Customers Near Little Jamaica in Toronto"
};
